spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: sope
      password: testapp
  logging:
    level:
      root:
        debug
  mail:
    host: smtp.gmail.com
    port: 587
    username: adebawojomosope@gmail.com
    password: xnao ekrg doum czwa
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
global:
  admin:
    email: globaladmin@gmail.com
    password: SuperSecret123
    firstName: Mosopefoluwa
    lastName: Adebawojo
    role: GLOBAL_ADMIN
